### ISSUE TITLE
Missing `Invoice.settings`

### ISSUE THREAD

**Issue by luxflux** [huerlisi/bookyt#88]
On the ESR file detail view (http://lala.wtag-accounts.dev/de-CH/esr_files/1), when trying to click on `book_extra_earnings`, an error is raised, see the following stack trace. Unfortunately I don't understand why it even tries to use `Invoice.settings`.

Could it be that this has been changed and should be a tag now?

```
NoMethodError (undefined method `settings' for #<Class:0x007fb1a35ec070>):
  activerecord (3.2.22) lib/active_record/dynamic_matchers.rb:55:in `method_missing'
  /Users/raf/projects/wtag/vesr/app/models/esr_record.rb:243:in `create_extra_earning_booking'
  /Users/raf/projects/wtag/vesr/app/controllers/esr_records_controller.rb:30:in `book_extra_earning'
  actionpack (3.2.22) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (3.2.22) lib/abstract_controller/base.rb:167:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (3.2.22) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
  activesupport (3.2.22) lib/active_support/callbacks.rb:480:in `_run__801331091404556896__process_action__1602121243709573793__callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22) lib/abstract_controller/callbacks.rb:17:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `block in instrument'
  activesupport (3.2.22) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (3.2.22) lib/active_support/notifications.rb:123:in `instrument'
  actionpack (3.2.22) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
  actionpack (3.2.22) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
  activerecord (3.2.22) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (3.2.22) lib/abstract_controller/base.rb:121:in `process'
  actionpack (3.2.22) lib/abstract_controller/rendering.rb:45:in `process'
  actionpack (3.2.22) lib/action_controller/metal.rb:203:in `dispatch'
  actionpack (3.2.22) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
  actionpack (3.2.22) lib/action_controller/metal.rb:246:in `block in action'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `call'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:36:in `call'
  journey (1.0.4) lib/journey/router.rb:68:in `block in call'
  journey (1.0.4) lib/journey/router.rb:56:in `each'
  journey (1.0.4) lib/journey/router.rb:56:in `call'
  actionpack (3.2.22) lib/action_dispatch/routing/route_set.rb:608:in `call'
  apartment (1.0.2) lib/apartment/reloader.rb:18:in `call'
  apartment (1.0.2) lib/apartment/elevators/generic.rb:23:in `call'
  pdfkit (0.6.2) lib/pdfkit/middleware.rb:17:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `catch'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
  rack (1.4.7) lib/rack/etag.rb:23:in `call'
  rack (1.4.7) lib/rack/conditionalget.rb:35:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/head.rb:14:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/flash.rb:242:in `call'
  rack (1.4.7) lib/rack/session/abstract/id.rb:210:in `context'
  rack (1.4.7) lib/rack/session/abstract/id.rb:205:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/cookies.rb:341:in `call'
  activerecord (3.2.22) lib/active_record/query_cache.rb:64:in `call'
  activerecord (3.2.22) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
  activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `_run__2837755033022701599__call__2373943768823666161__callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:405:in `__run_callback'
  activesupport (3.2.22) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
  activesupport (3.2.22) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (3.2.22) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/reloader.rb:65:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
  railties (3.2.22) lib/rails/rack/logger.rb:32:in `call_app'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `block in call'
  activesupport (3.2.22) lib/active_support/tagged_logging.rb:22:in `tagged'
  railties (3.2.22) lib/rails/rack/logger.rb:16:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (3.2.22) lib/action_dispatch/middleware/request_id.rb:22:in `call'
  rack (1.4.7) lib/rack/methodoverride.rb:21:in `call'
  rack (1.4.7) lib/rack/runtime.rb:17:in `call'
  activesupport (3.2.22) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
  rack (1.4.7) lib/rack/lock.rb:15:in `call'
  actionpack (3.2.22) lib/action_dispatch/middleware/static.rb:83:in `call'
  railties (3.2.22) lib/rails/engine.rb:484:in `call'
  railties (3.2.22) lib/rails/application.rb:231:in `call'
  railties (3.2.22) lib/rails/railtie/configurable.rb:30:in `method_missing'
  unicorn (4.8.3) lib/unicorn/http_server.rb:576:in `process_client'
  unicorn (4.8.3) lib/unicorn/http_server.rb:670:in `worker_loop'
  unicorn (4.8.3) lib/unicorn/http_server.rb:525:in `spawn_missing_workers'
  unicorn (4.8.3) lib/unicorn/http_server.rb:140:in `start'
  unicorn (4.8.3) bin/unicorn_rails:209:in `<top (required)>'
  /opt/boxen/rbenv/versions/2.2.2/bin/unicorn_rails:23:in `load'
  /opt/boxen/rbenv/versions/2.2.2/bin/unicorn_rails:23:in `<main>'
```

**Comment by huerlisi** [comment]
Yepp, that's right. Tags are a bit of a loose interface, but either we directly use it or we put some facade in from of it.

I think we should be pragmatic and just go with porting to tags.

**Comment by luxflux** [comment]
Okay, I will change this to use tags.

Regarding a solid structure for these labels, I am thinking about a database table like this:

label | account_id
--- | :---:
invoice:costs | 1
invoice:earnings | 2
... | ...
whatever:somewhere | 1

And you would have an interface to define the required labels with a descriptive text. It would also allow you to define additional labels.

How does this sounds like to you? Does it make any sense?
What do you think how much work would it be to establish such a mapping system?
